import{S as u,i as c}from"./assets/vendor-0fc460d7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();async function d(t){const r=`https://pixabay.com/api/?${t}`,n=await fetch(r);if(!n.ok)throw new Error("Network response was not ok");return n.json()}function m(t){return new Promise((r,n)=>{const s=t.map(e=>new Promise((o,a)=>{const i=new Image;i.onload=o,i.onerror=a,i.src=e.largeImageURL}));Promise.all(s).then(r).catch(n)})}async function f(t){try{y(),await p(),await m(t);const r=document.querySelector("ul");if(!r)throw new Error("List element not found");const n=t.slice(0,9);r.insertAdjacentHTML("beforeend",h(n));const s=new u("ul a",{captionsData:"alt",captionDelay:250});l()}catch(r){console.error("Error while preloading images:",r),l()}}async function p(){const t=document.querySelector("ul");t&&(t.innerHTML="")}function h(t){return t.map(({webformatURL:r,largeImageURL:n,tags:s,likes:e,views:o,comments:a,downloads:i})=>`
        <li>
    <a href="${n}" alt="${s}">
        <img src="${r}" alt="${s}" width="360"  />
       <p class="image-info" >
    <span>Likes<br> ${e}</span>
    <span>Views<br> ${o}</span>
    <span>Comments<br> ${a}</span>
    <span>Downloads<br> ${i}</span>
         </p>
     </a>
       </li>
        `).join("")}function y(){const t=document.querySelector(".loader");t&&(t.style.display="block")}function l(){const t=document.querySelector(".loader");t&&(t.style.display="none")}document.addEventListener("DOMContentLoaded",function(){const t=document.querySelector("button[data-start]"),r=document.getElementById("search-img"),n="43273771-9fb27172998fac0872066584a";t.addEventListener("click",async()=>{const s=r.value.trim();if(s)try{const e=new URLSearchParams({key:n,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"}),o=await d(e);if(o.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");f(o.hits,"ul.gallery"),r.value=""}catch(e){r.value="",c.error({title:"Error",message:e.message,position:"topRight"})}else c.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"})})});
//# sourceMappingURL=commonHelpers.js.map
