import{S as u,i as l}from"./assets/vendor-0fc460d7.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();function d(e){const t=`https://pixabay.com/api/?${e}`;return fetch(t).then(n=>{if(!n.ok)throw new Error("Network response was not ok");return n.json()}).catch(n=>{throw console.error("Error while fetching images:",n),n})}let c;function m(e){return new Promise((t,n)=>{const s=e.map(r=>new Promise((o,i)=>{const a=new Image;a.onload=o,a.onerror=i,a.src=r.largeImageURL}));Promise.all(s).then(t).catch(n)})}function f(e){g(),h().then(()=>m(e)).then(()=>{const t=document.querySelector("ul");if(!t)throw new Error("List element not found");t.insertAdjacentHTML("beforeend",p(e)),c?c.refresh():c=new u("ul a",{captionsData:"alt",captionDelay:250}),y()}).catch(t=>{console.error("Error while preloading images:",t)})}function h(){return new Promise(e=>{const t=document.querySelector("ul");t&&(t.innerHTML=""),e()})}function p(e){return e.map(({webformatURL:t,largeImageURL:n,tags:s,likes:r,views:o,comments:i,downloads:a})=>`
            <li>
                <a href="${n}" alt="${s}">
                    <img src="${t}" alt="${s}" width="360" />
                    <p class="image-info">
                        <span>Likes<br> ${r}</span>
                        <span>Views<br> ${o}</span>
                        <span>Comments<br> ${i}</span>
                        <span>Downloads<br> ${a}</span>
                    </p>
                </a>
            </li>
        `).join("")}function g(){const e=document.querySelector(".loader");e&&(e.style.display="block")}function y(){const e=document.querySelector(".loader");e&&(e.style.display="none")}document.addEventListener("DOMContentLoaded",function(){const e=document.querySelector("button[data-start]"),t=document.getElementById("search-img"),n="43273771-9fb27172998fac0872066584a";e.addEventListener("click",()=>{const s=t.value.trim();if(s){const r=new URLSearchParams({key:n,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"});d(r).then(o=>{if(o.hits.length===0)throw w(),L(),new Error("Sorry, there are no images matching your search query. Please try again!");f(o.hits),t.value=""}).catch(o=>{t.value="",l.error({title:"Error",message:o.message,position:"topRight"})})}else l.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"})})});function w(){return new Promise(e=>{const t=document.querySelector("ul");t&&(t.innerHTML=""),e()})}function L(){const e=document.querySelector(".loader");e&&(e.style.display="block")}
//# sourceMappingURL=commonHelpers.js.map
